#  menu items
[[main]]
  name = "Blog"
  weight = 1
  url = "blog/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"

[[main]]
  name = "Tutorials"
  weight = 2
  url = "tutorials/"

[[main]]
  name = "About us"
  weight = 3
  url = "https://docs.neuralvibes.com"

# [[main]]
#   name = "Blog"
#   weight = 4
#   url = "blog/"